# Generated by Django 4.1.4 on 2022-12-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("phone_nr", models.CharField(max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("terms", models.BooleanField(default=False, null=True)),
                ("gender", models.CharField(max_length=8, null=True)),
                ("weight", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("time", models.FloatField(null=True)),
                ("category", models.CharField(max_length=40, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Booking date")),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_fname", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=30, null=True)),
                ("nop", models.IntegerField()),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking",
                        to="website.service",
                    ),
                ),
            ],
        ),
    ]
