# Generated by Django 4.1.4 on 2022-12-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_customer_date_added"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="date_added",),
        migrations.AddField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="modified",
            field=models.DateTimeField(null=True),
        ),
    ]
