# Generated by Django 4.1.4 on 2023-01-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_customer_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complete", models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="credit",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="credit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service",
                to="website.service",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visa", models.IntegerField(blank=True, null=True)),
                ("cash", models.IntegerField(blank=True, null=True)),
                ("other", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, max_length=100)),
                ("created", models.DateField(editable=False, null=True)),
                ("modified", models.DateField(editable=False, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                ("created", models.DateField(editable=False, null=True)),
                ("modified", models.DateField(editable=False, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.service",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.customer",
            ),
        ),
    ]
