# Generated by Django 4.1.4 on 2023-01-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_customer_cash_credit_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
