# Generated by Django 4.1.4 on 2023-01-13 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0008_orderitem_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UN", "Unsigned"),
                            ("I", "Instructor"),
                            ("A", "Assistant"),
                            ("BA", "B-Assistant"),
                            ("R", "Reception"),
                            ("M", "Manager"),
                            ("HI", "Head instructor"),
                        ],
                        default="UN",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField(default=0)),
                (
                    "service",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.service",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.staff",
                    ),
                ),
                ("student", models.ManyToManyField(to="website.customer")),
            ],
        ),
    ]
