# Generated by Django 4.1.4 on 2023-01-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_alter_customer_user_alter_session_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.service",
            ),
        ),
    ]
