# Generated by Django 4.1.4 on 2023-01-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_alter_session_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="commission",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
